# Generated by Django 5.1.7 on 2025-03-27 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Py_objects',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок метода')),
                ('name', models.CharField(max_length=25, verbose_name='Название метода')),
                ('description', models.TextField(verbose_name='Название')),
                ('example_code_image', models.ImageField(upload_to='py_objects_images/', verbose_name='Пример кода метода')),
            ],
        ),
    ]
